### ISSUE TITLE
Эндпоинт Художник (GET, POST, PATCH)

### ISSUE THREAD

**Issue by Edelveisx** [Sagaart-wold/backend#34]

**Comment by Badmajor** [comment]
@Edelveisx у нас есть информация, какие поля для художника нужны фронту,
https://app.swaggerhub.com/apis/GLADKOVAKO29/Registration/1#/%D0%A3%D1%87%D1%91%D1%82%D0%BD%D0%B0%D1%8F%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C

тут нет вообще этого эндпоинта.
